server:
  port: 8080

spring:
  application:
    name: WebHookService

  liquibase:
    liquibase-schema: ${LIQUIBASE_SCHEMA:public}
    enabled: false

  datasource:
    url: ${env.DB_URL}
    username: ${env.DB_USER}
    password: ${env.DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 2

telegram:
  api-url: "https://api.telegram.org"
  webhook-path: "${env.SERVER_URL}/bot/webhook"
  bot-name: ${env.BOT_NAME}
  bot-token: ${env.BOT_TOKEN}



