name: Deploy to Tomcat

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Properties
        run: |
          echo "db.url=${{ secrets.BOT_DB_URL }}" >> $GITHUB_ENV
          echo "db.user=${{ secrets.BOT_DB_USER }}" >> $GITHUB_ENV
          echo "db.password=${{ secrets.BOT_DB_PASS }}" >> $GITHUB_ENV     
          echo "tomcat.url=${{ secrets.SERVER_URL }}" >> $GITHUB_ENV
          echo "tomcat.user=${{ secrets.TOMCAT_USERNAME }}" >> $GITHUB_ENV
          echo "tomcat.password=${{ secrets.TOMCAT_PASSWORD }}" >> $GITHUB_ENV

      - name: Deploy to Tomcat
        run: mvn tomcat7:deploy -DskipTests
        env:
          SERVER_URL: ${{ secrets.SERVER_URL }}
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
          BOT_DB_URL: ${{ secrets.BOT_DB_URL }}
          BOT_DB_USER: ${{ secrets.BOT_DB_USER }}
          BOT_DB_PASS: ${{ secrets.BOT_DB_PASS }}