name: Java Maven Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Maven Properties for jOOQ
        run: |
          echo "db.url=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "db.user=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "db.password=${{ secrets.DB_PASS }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install -DskipTests
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASS }}